name: Update M3U
on:
  push:
    paths:
      - 'MacDataBase.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Generate File
        run: python generate_m3u.py
      - name: Push Back
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Auto update playlist" || exit 0
          git push
